# Generated by Django 4.1.5 on 2023-01-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pre', models.CharField(max_length=50)),
                ('date_n', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('mail', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('m_p', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('pays', models.CharField(max_length=50)),
                ('PROVINCE', models.CharField(max_length=50)),
                ('région', models.CharField(max_length=50)),
                ('addresse', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='photos/resto')),
                ('specialite', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('etoiles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('prix', models.DecimalField(decimal_places=3, max_digits=5)),
                ('img', models.ImageField(upload_to='photo/plat')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
            ],
        ),
        migrations.CreateModel(
            name='Commantair_plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField()),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.plat')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement_resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
