# Generated by Django 4.2.2 on 2024-05-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('pays', models.CharField(max_length=50)),
                ('gouvernement', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('addresse', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='resto')),
                ('specialite', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('etoiles', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='plat')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='evenement')),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
            ],
        ),
        migrations.CreateModel(
            name='Commantair_plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField()),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.plat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement_resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
