# Generated by Django 4.2.2 on 2024-05-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_users'),
        ('resto', '0002_alter_abonnement_resto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement_resto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='commantair_plat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='resto',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
