# Generated by Django 4.1.5 on 2023-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_rename_province_resto_gouvernement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='img',
            field=models.ImageField(upload_to='photos/plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='resto',
            name='img',
            field=models.ImageField(upload_to='resto'),
        ),
    ]
