# Generated by Django 4.1.5 on 2023-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_plat_active_alter_plat_img_alter_plat_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='img',
            field=models.ImageField(upload_to='plat'),
        ),
    ]
