# Generated by Django 4.1.5 on 2023-02-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_alter_plat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commantair_plat',
            name='resto',
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='evenement')),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.resto')),
            ],
        ),
    ]
