# Generated by Django 4.1.5 on 2023-02-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_alter_evenement_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='img',
            field=models.ImageField(upload_to='evenement'),
        ),
    ]
