# Generated by Django 4.1.5 on 2023-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='img',
            field=models.ImageField(upload_to='pub'),
        ),
    ]
