# Generated by Django 4.1.5 on 2023-01-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pre', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='photo/users')),
                ('pays', models.CharField(max_length=50)),
                ('PROVINCE', models.CharField(max_length=50)),
                ('région', models.CharField(max_length=50)),
                ('date_n', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('mail', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('m_p', models.CharField(max_length=50)),
            ],
        ),
    ]
