# Generated by Django 4.1.5 on 2023-02-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PROVINCE',
            new_name='gouvernement',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='région',
            new_name='region',
        ),
    ]
