# Generated by Django 4.1.5 on 2023-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_province_user_gouvernement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='static/image/icon/user.jpg', upload_to='users'),
        ),
    ]
